// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace demo {
	
	
	public partial class multiview1 {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.MultiView mtv_View;
		
		protected System.Web.UI.WebControls.View view1;
		
		protected System.Web.UI.WebControls.TextBox name1;
		
		protected System.Web.UI.WebControls.Button btn1;
		
		protected System.Web.UI.WebControls.View view2;
	}
}
