// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace demo {
	
	
	public partial class WizardDemo1 {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Wizard wz1;
		
		protected System.Web.UI.WebControls.WizardStep step1;
		
		protected System.Web.UI.WebControls.WizardStep step2;
	}
}
