// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace demo {
	
	
	public partial class wizardDemo {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Wizard Wizard1;
		
		protected System.Web.UI.WebControls.WizardStep WizardStep1;
		
		protected System.Web.UI.WebControls.TextBox txtFirstName;
		
		protected System.Web.UI.WebControls.TextBox txtLastName;
		
		protected System.Web.UI.WebControls.DropDownList ddlGender;
		
		protected System.Web.UI.WebControls.WizardStep WizardStep3;
		
		protected System.Web.UI.WebControls.TextBox txtEmail;
		
		protected System.Web.UI.WebControls.TextBox txtMobile;
		
		protected System.Web.UI.WebControls.WizardStep WizardStep2;
		
		protected System.Web.UI.WebControls.Label lblFirstName;
		
		protected System.Web.UI.WebControls.Label lblLastName;
		
		protected System.Web.UI.WebControls.Label lblGender;
		
		protected System.Web.UI.WebControls.Label lblEmail;
		
		protected System.Web.UI.WebControls.Label lblMobile;
	}
}
